### ISSUE TITLE
README File is Empty

### ISSUE THREAD

**Issue by sudo-adi** [MahajanPreksha/Test-Repo#1]
Description: The README.md file in the repository is currently empty. A well-documented README is crucial for understanding the purpose of the project, its setup, usage instructions, and contribution guidelines.

**Comment by sudo-adi** [comment]
Can i work on this issue?

**Comment by MahajanPreksha** [comment]
Yes

**Comment by sudo-adi** [comment]
@MahajanPreksha  Can you please review pr
